services:
  caddy:
    # Custom Caddy build with Cloudflare DNS module for ACME DNS challenge
    image: caddy-cloudflare
    build: .
    restart: unless-stopped
    container_name: caddy    env_file: ./.env    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/dockerdata/caddy/data:/data
      - /opt/dockerdata/caddy/config:/config
    networks:
      - caddy_network

networks:
  caddy_network:
    name: caddy_network
    driver: bridge